name: Force check every file for UUID and add it if missing

on:
  workflow_dispatch:

jobs:
  add_uuid:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: run script
        run: |
          python3.12 add_uuid_to_md_missing_one.py

      - name: Check for changes
        id: git-check
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            exit 0;
          else
            exit 1;
          fi 

      - name: Commit
        if: steps.git-check.outcome == 'success'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
            commit_message: Add UUID to missing files
            file_pattern: '*.md'
            status_options: '--untracked-files=no'

      - name: Push changes
        if: steps.git-check.outcome == 'success'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.REF }}

